version: '2'

services:
    mtproxy:
        image: kolahzary/mtproxy:1.0 # MTProxy docker image without hard-coded limitations
        ports:
          - "443:443" #Proxy port
          - "127.0.0.1:2398:2398" # Show proxy stats on local port 2398 outside of docker
        volumes:
           - "./mtproxy-data:/data"
        restart: unless-stopped
        env_file:
           - ./config.env
